# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  cypress: cypress-io/cypress@2.2.0

# Invoke jobs via workflows
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm install
      - cypress/run:
          verify-command: npx cypress run -b chrome -s "cypress/e2e/api.test.automation.cy.js" 
